CREATE TABLE IF NOT EXISTS notes
(
    Id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    "Text" TEXT NULL,
    CreatedOn TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ModifiedOn TIMESTAMPTZ NULL,
    NoteVersion INTEGER NOT NULL DEFAULT 1,
    DeletedOn TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS IX_notes_Active_Id
    ON notes (Id)
    WHERE DeletedOn IS NULL;
